### ISSUE TITLE
Issues detecting network interfaces

### ISSUE THREAD

**Issue by andreaciriello** [stevenshiau/drbl#30]
Hi, I'm trying to set up a DRBL server to do network backups of all my PCs, but I'm having trouble setting up the NICs.

My setup is this: the PC is a virtual machine running on TrueNAS CORE and the OS is Ubuntu Server 23.10. The network service running on it is netplan. The virtual machine has two NICs and they show in Ubuntu as different network interfaces. When I try to run "drblpush -i" the setup stops after setting the client hostname prefix saying "You did NOT setup any Internet network settings for the network cards for the clients (such as the IP address of eth1, eth2, ...), or something wrong!"

If I list the network interfaces, they don't show as ethx, but as enp0sx.

Does drbl expect to find networks named ethx? Or am I missing something?
Can you give me some hints?

Thank You in advance for your time.

**Comment by stevenshiau** [comment]
"Does drbl expect to find networks named ethx?" -> No. Device name like eno1 will be fine. too.
If you run command "ip add", what's the result?

Steven

**Comment by andreaciriello** [comment]
![image](https://github.com/stevenshiau/drbl/assets/16070979/6f3f3222-2fe3-4f46-b15c-9ad9fcb5c571)
@stevenshiau this is what I get when I run "ip add". Each adapter (virtual ones too) has its own IP address.

**Comment by stevenshiau** [comment]
Did you set any default gateway?
What's the results if you run "ip route"?

Steven

**Comment by andreaciriello** [comment]
![image](https://github.com/stevenshiau/drbl/assets/16070979/52b9a081-0300-494d-b340-0f70f5903831)
@stevenshiau This is what I get when I run ip route.
"Did you set any default gateways?" -> Yes, the default gateway is my router on both interfaces enp0s5 and enp0s6.

**Comment by stevenshiau** [comment]
It's confusing actually. You do not have to hide your IP address because 192.168 is the private IP address. It's not unique. It's everywhere.
Otherwise how will we know if you really setup the correct IP address? To me, only on default gw is required. You have configured two, and it an issue I believe.

Steven

**Comment by andreaciriello** [comment]
Output of ip add:
![image](https://github.com/stevenshiau/drbl/assets/16070979/d929f2f1-8245-41ba-ba2c-b8f1f6f150d4)

Output of ip route:
![image](https://github.com/stevenshiau/drbl/assets/16070979/21521a57-b98a-4711-9794-920a422ed347)

I tried to remove one of the default gateways (which had the same ip address as the remaining one), but still no luck.

**Comment by stevenshiau** [comment]
Please set different network subsets for your network devices, e.g., 
eth0: 192.168.1.254/24
eth1: 192.168.2.254/24
enp0s5: 192.168.11.254/24
enp0s6: 192.168.12.254/24

Steven

**Comment by andreaciriello** [comment]
@stevenshiau Sorry for late response. I found out what was the problem: the script was looking for the command 'ifconfig' which, on newer versions of Ubuntu Server, is not installed by default. I installed the package net-tools and now it works. Still, I treasured your suggestions.

Thank you.

**Comment by stevenshiau** [comment]
OK, got it.
However, if you follow the docs on https://drbl.org/installation/ to install and configure DRBL/Clonezilla. In the step "drblsrv -i" , it should install that for you.

Steven
