### ISSUE TITLE
systemd 227 and /etc/mtab being a regular file

### ISSUE THREAD

**Issue by haste** [stevenshiau/drbl#4]
systemd 227[0] enforces that /etc/mtab isn't a regular file and freezes the system during boot if it is. This is only a temporary issue as the behavior is patched[1] away in the next version of systemd.

A temporary workaround is to create a symlink instead in init.drbl:
```diff
diff --git a/setup/files/misc/init.drbl b/setup/files/misc/init.drbl
index 73ea98a..f8e5e8d 100755
--- a/setup/files/misc/init.drbl
+++ b/setup/files/misc/init.drbl
@@ -352,11 +352,7 @@ maybe_break drbl_postnfs
 rm -f /etc/mtab /etc/mtab~ /etc/mtab~~ /etc/nologin
 
 # if, for any reason, mtab was not synced with what it should be, Sync it.
-while read ilist; do
-  # skip the "rootfs / rootfs rw 0 0" 
-  [ -n "$(echo $ilist | grep -E "^rootfs \/ rootfs .*")" ] && continue
-  echo $ilist >> /etc/mtab
-done < /proc/mounts
+ln -sf /proc/mounts /etc/mtab
 
 # umount the useless /initrd/proc and /initrd if they exist.
 for i in /initrd/proc /initrd; do
```

I'm not familiar enough with the internals to know if this creates any issues (due to rootfs not being removed), but it works in our current setup.

systemd 227 is currently used in Debian Stretch and Sid.

[0] http://lists.freedesktop.org/archives/systemd-devel/2015-October/034509.html
[1] https://github.com/systemd/systemd/commit/5dea1c1e7902ca07ca1ea7f1914031c6e3a27be5

**Comment by stevenshiau** [comment]
Forgot to mention this patch has been applied 2 weeks ago.
Thanks.

Steven.
