### ISSUE TITLE
Clarify g parameter

### ISSUE THREAD

**Issue by mirh** [stevenshiau/drbl#8]
Specifically [this](https://github.com/stevenshiau/drbl/blob/master/lang/bash/en_US#L621). 
Is it still performing grub config file check?
If not, why is such an "altering" option enabled by default in Clonezilla?

And is it normal the parameter in sourced is called "msg_ocs_onthefly_param_g" even though (at least in disk_to_local_disk mode) it is called "-g auto" then? Like [here](http://clonezilla.org/clonezilla-live/doc/02_Restore_disk_image/advanced/09-advanced-param.php) but with the aforementioned description.

**Comment by stevenshiau** [comment]
Batch mode is dangerous because it won't ask you to confirm before overwriting the destination disk/partition.
"msg_ocs_onthefly_param_g"  is just a variable for "-g auto". Of course, we can called it "msg_ocs_onthefly_param_g_auto".

Steven

**Comment by mirh** [comment]
Uh, no man, sorry. You updated the thing just hours after my post and line number changed. 
I was referring to this https://github.com/stevenshiau/drbl/blob/ebf05e0d27ea87246c34b67c330d6f5a91590cbc/lang/bash/en_US#L621
